FROM cassandra:2.1.20
MAINTAINER ram
#VOLUME ['/usr/share/nginx/html']
#COPY ./nginx/html /usr/share/nginx/html
#COPY ['./nginx/Pictures','/opt']
#ADD ['./nginx/cram-md5.py.tar.gz','/opt']
#RUN pwd
#WORKDIR /opt
#RUN pwd
#RUN /bin/bash -c 'alias ll='ls -al';ll'
#EXPOSE 80